### ISSUE TITLE
capf icon error 

### ISSUE THREAD

**Issue by donneyluck** [shuxiao9058/tabnine#1]
![image](https://github.com/shuxiao9058/tabnine/assets/122257591/d14e5141-392d-444c-96e3-705a4e5cd316)

what should i do

emacs 29.1
manjaro linux  last

**Comment by shuxiao9058** [comment]
could you share your config file? Which frontend do you use? company or corfu?

**Comment by shuxiao9058** [comment]
perhaps this is because the company kind:

```
     :company-kind (lambda (_) (intern "tabnine"))
```

try add kind icon :

```

 (add-to-list 'kind-icon-mapping '(tabnine "ai" :icon "cloud" :face shadow) t)
```

**Comment by shuxiao9058** [comment]
@donneyluck have you resolved this issue now?

**Comment by donneyluck** [comment]
> @donneyluck have you resolved this issue now?
 resolved thanks
