### ISSUE TITLE
[Improvement] Display requirements in README 

### ISSUE THREAD

**Issue by liar666** [shuxiao9058/tabnine#10]
I could not manage to install `tabnine`+`company-tabnine` for some time.

After discovering & trying the DoomEmacs Sandbox, and trying to install `tabnine`/`company-tabnine` from there, I discovered an error message on a failing emacs-29.1 requirement.

So I finally understood that probably `tabnine`/`company-tabnine` requires Emacs 29+, whereas I was using 28.1.

It would be great if these minimal requirements could be displayed somewhere, e.g. in the README page, so that people do not waste hours trying to find out why `tabnine`/`company-tabnine` is not installing on their machine.

Thanks in advance

**Comment by shuxiao9058** [comment]
sorry for the mislead upgrade to 29.1,  this issue is caused by resolve another issue(a46629994b485472a442517e4c287e7a493deb9e)
