### ISSUE TITLE
Support for switchable models in tabnine chat

### ISSUE THREAD

**Issue by PGKANG** [shuxiao9058/tabnine#12]
Tabnine chat support switchable models now. Is it possible to support this feature just like vscode? A lot of thanks in advance.

**Comment by shuxiao9058** [comment]
It seems that my account can not switch the model yet.

**Comment by shuxiao9058** [comment]
I have contact the TabNine team, this is the answer

```
Thanks for confirming that you have the legacy account.
 
The subscription that you have-- Tabnine Pro Personal, does not support Chat. You will need to change to Tabnine Pro Teams to access chat.
 
If you like, I can cancel the old subscription that you have and provide you with Tabnine Pro free for one year. After one year, you will be charged $144 which is the regular price.
```

So, the new feature is not available with my account.

Also PR is welcome.

**Comment by jleechpe** [comment]
I was trying to look into this (especially since they keep adding new models and it is now generally available), but they don't seem to have any API docs for how to specify which model to use (or even for any of the data you already used in chat.  Is this something they provided directly when you reached out?

**Comment by PGKANG** [comment]
I didn't find any docs either. I tried this new feature in vscode.

**Comment by shuxiao9058** [comment]
You can capture packets and analyze the details.

**Comment by jleechpe** [comment]
I was able to find the modelIds and it appeared to do something when I changed them (I can't get TabNine Chat to actually tell me which model it's running so I'm relying on differences in output style) but I could only get TabNine Protect and TabNine + Mistral to work.  All the other (non-private) ones threw Unauthorized errors even though the payload looked like extremely similar to what VSCode was sending.

**Comment by shuxiao9058** [comment]
@jleechpe @PGKANG Done
