### ISSUE TITLE
Tabnine error on `editorconfig--get-indentation-lisp-mode` in `.el` files

### ISSUE THREAD

**Issue by jleechpe** [shuxiao9058/tabnine#13]
Similar to the error you fixed in a466299 but for `emacs-lisp-mode`.

For the time being I'm using

```lisp
(add-to-list 'tabnine-util--indentation-alist '(emacs-lisp-mode lisp-indent-offset))
```

**Comment by shuxiao9058** [comment]
It seems that there is no need to add this code, because it is included in editorconfig package.

**Comment by shuxiao9058** [comment]
It seems that the editorconfig you use is not the [official version]( https://github.com/editorconfig/editorconfig-emacs)。

**Comment by jleechpe** [comment]
I was about to comment with a link to the file in savannah. 

What is really interesting is that the github repo is fairly up-to-date but differs on that line (and on lisp mode and possibly a few others).
