### ISSUE TITLE
Change license from MIT to GPLv3

### ISSUE THREAD

**Issue by shuxiao9058** [shuxiao9058/tabnine#3]
As this project use large chunk code from https://github.com/karthink/gptel and discussed at https://github.com/karthink/gptel/issues/91, I prefer change the license from MIT to GPLv3.

This issue is primarily for discussing this decision.

For more information on GPLv3 please read: https://www.gnu.org/licenses/quick-guide-gplv3.html

Tasks:
- [x] Ask contributors approve this decision
  - [x] @TommyX12
  - [x] @50ways2sayhard
  - [x] @cireu
  - [x] @xqliu
  - [x] @MatthewZMD
  - [x] @kisaragi-hiu
  - [x] @yqrashawn
  - [x] @zerolfx
  - [x] @karthink

- [x] Change the license to the README and Code
- [x] Add license badge to README.md
- [x] Include license file within project

**Comment by MatthewZMD** [comment]
Approve.

**Comment by xqliu** [comment]
LGTM !

**Comment by kisaragi-hiu** [comment]
I approve.

**Comment by TommyX12** [comment]
LGTM :)

**Comment by zerolfx** [comment]
LGTM

**Comment by yqrashawn** [comment]
LGTM

**Comment by karthink** [comment]
Thanks, please go ahead.

**Comment by yongqiang23** [comment]
LGTM

**Comment by shuxiao9058** [comment]
Since can not contact with @cireu , so I will change the license directly.

**Comment by cireu** [comment]
Approved, sorry for the late reply!

**Comment by shuxiao9058** [comment]
> Approved, sorry for the late reply!

Thanks for your reply.
