### ISSUE TITLE
Not working: set tabnine--access-token to nil.

### ISSUE THREAD

**Issue by liar666** [shuxiao9058/tabnine#4]
When I use `tabnine-chat` and send some query with `C-c RET`, I get error:
```
TabNine token is expired, set tabnine--access-token to nil.
```

I'm not sure if it means that your package complains that the var is nil when it should have a token in it or if it means I need to actually set the variable to nil. 

- I did set the var to nil and got the same error.

- I've searched for "token" and "access" on your github's README, but these keywords do not appear. I don't know how to get a token and how to configure your package with it, if this is what is needed.

**Comment by shuxiao9058** [comment]
while failed get result from tabnine chat (404 not found), this may means token expired or no access to the tabnine chat, set the variable to nil, so will retrieve token next time.

**Comment by shuxiao9058** [comment]
If you do not have access to the tabnine chat , please email to the tabnine team join beta test.

**Comment by liar666** [comment]
Hi,
Thanks for the quick answer.

- I've set the variable to nil, but I get the same error
- I've contacted the TabNine team a few days back, but for the moment I only received an email saying `Thanks for signing up for Tabnine Chat beta - we’ll be in touch soon.`. Even if they provide a token or create an account for me on their website, I don't know what to do with it (there no information in your README...).

**Comment by shuxiao9058** [comment]
The token should get from tabnine process. and you can execute `tabnine-capabilities` function to see whether you have the tabnine chat feature.

also you can try with vscode to test whether the tabnine chat can works well too.

**Comment by shuxiao9058** [comment]
@liar666 You can see the latest README about the setup, if you have any question, please leave a comment.

**Comment by shuxiao9058** [comment]
@liar666 have you resolved this issue?

**Comment by rdtf666** [comment]
Sorry I still haven't received the token yet :(
Apparently folks at TaBnine are burried under requests for trial :(

**Comment by shuxiao9058** [comment]
You must join the BETA test before using TabNine Chat ... @rdtf666

**Comment by liar666** [comment]
Hi,

I just received TabNine's answer, but there's no token in sight :(

Here is their email:
----
Hey XXX,

Good news! You’ve been chosen to be part of our Tabnine Chat Beta program. We’re thrilled to have you on board!

Tabnine Chat is currently available in VS Code and JetBrains IDEs, and supports all the popular programming languages.

To get started, follow these steps:

    Install or update to the latest version of Tabnine’s extension for VS Code or JetBrains
    Log in to your IDE with tabnine.gmuller@erine.email
    Restart your IDE
    Click on the Tabnine icon located on the left sidebar (VS Code) or right sidebar (JetBrains)
    If you do not see the Tabnine Chat UI, wait another minute and restart again. If you still do not see it, contact [support@tabnine.com](mailto:support@tabnine.com)
    You’re all set! Start chatting with Tabnine. 

To help you get started, [here's a video](...) that covers the basics of using Tabnine Chat.

We’re eager to hear about your experience with Tabnine Chat. Feel free to reach out to [feedback@tabnine.com](mailto:feedback@tabnine.com) to share your thoughts and provide any feedback you may have.

Thank you for joining us on this exciting journey!

Best regards,

Tabnine Team
---

I logged-in in VSCodium, and everything (chat included) works there.

Also, I created an account on the TabNine website, but I don't see any place to get a token. Also on the website Chat is not available, they ask to register for a 14-day trial, which requires CB number. It's a no-go for me...

If you have any idea where I can get the famous token....

Thanks for the help

**Comment by shuxiao9058** [comment]
The token is get from tabnine process(tabnine api service), so you do not care about it, you should login your account in tabnine configuration page.Then enjoy tabnine chat.

**Comment by shuxiao9058** [comment]
@liar666 

have you resolved now?

**Comment by fsc-eriker** [comment]
I seem to be experiencing the same problem, though I don't get an actual error, just a status message at the top of the `*tabnine-chat*` buffer. `tabnine-configuration` brings up a web page with my account properly signed in, and TabNine code completion works fine, but `tabnine-chat` immediately gives me `Response Error: TabNine token expired`. Chat works fine in VS Code.

`tabnine-capabilities` does not include anything about chat.

I only just configured this package in Emacs. Is there something more I need to do in order to properly log myself in to the service or something?

**Comment by shuxiao9058** [comment]
@fsc-eriker 

Sorry for that, I have found the issue now, and will be fixed later this week(maybe this weekend).(TabNine is deprecated the old api protocol, and the latest api version is v3)

**Comment by shuxiao9058** [comment]
Hi, @fsc-eriker , you can try with the latest version, once any issue happened, please let me known, thanks.

**Comment by fsc-eriker** [comment]
@shuxiao9058 Thanks, I can confirm that upgrading to the latest version from MELPA sorted it for me.
