### ISSUE TITLE
Completely Disable Overlay

### ISSUE THREAD

**Issue by chall8908** [shuxiao9058/tabnine#7]
I have constant problems with the overlay from tabnine getting in the way of what I'm trying to do.  I really just want to use `capf` only and would like to completely disable the overlay so that company can do its thing.

I didn't see an obvious way to do this when looking in tabnine-core.

**Comment by shuxiao9058** [comment]
Hi, @chall8908 , thanks for your report, please update to the latest version, and disable tabnine-mode.

If it does't work, please let me know.
