### ISSUE TITLE
Cannot sign in using auth token

### ISSUE THREAD

**Issue by tillydray** [shuxiao9058/tabnine#8]
I signed out of my local configuration page and now I can't get emacs tabnine to use my credentials. This means I don't have access to my Pro features in Emacs.

1. I did `M-x tabnine-configuration`
2. It navigated me to my configuration page in the browser
3. I logged out by pressing "Log out" on the configuration page
4. I clicked "sign in"
5. It navigated me to https://app.tabnine.com/auth/sign-in/manual
6. The page says

```
Sign in using auth token
To sign in using auth token, follow these steps:

- Copy this token
    <redacted_token>
- Go to your IDE command palette
- Type Tabnine: Sign in using auth token
- Paste this token
```

7. I do not see any way to sign in with this auth token

In case it's relevant, 
```
tabnine--access-token is a variable defined in tabnine-core.el.

Value
nil

tabnine-access-token-expires-in is a customizable variable defined in
tabnine-core.el.

Value
2700
```

**Comment by shuxiao9058** [comment]
Sorry for the inconvenience, since the tabnine changed the auth method recently, but this package is not supported yet, but you can try with vscode to login your account. 

I will try to resolve this issue this weekend.

**Comment by shuxiao9058** [comment]
Hi, @tillydray with the latest version, you can login your account with `tabnine-login` command.

**Comment by tillydray** [comment]
@shuxiao9058 thanks it works! Happy Thanksgiving!
